### ISSUE TITLE
[DEV] Cours dupliqué changement de cours

### ISSUE THREAD

**Issue by lucas-luchack** [PapillonApp/papillon-v4#10]
Le précédent fix pour supprimer les cours dupliqués lors d'un changement de salle de professeur ou d'horaire etc... ne fonctionne pas.
Cela supprime le nouveau cours, il ne reste donc plus que le cours annulé.

**Comment by ecnivtwelve** [comment]
Normalement c'est fix (*n'hésite pas à réouvrir*)
