### ISSUE TITLE
[Bug]:  Non prise en compte des remplacements 

### ISSUE THREAD

**Issue by mlebrun40** [PapillonApp/papillon-v4#14]
### Description du bug

Les remplacements ne sont pas pris en compte sur l'emploi du temps 

### Etapes à reproduire

1. Emploi du temps

### Comportement attendu

Afficher le remplacement du cours 

### Appareil

Tous

### OS

Tous

### Version

Touq

### Environnement

PWA Dev (app.pronote.plus)

**Comment by lucas-luchack** [comment]
Fix mis en place (412aac84198770abc6b6f0cb3caf6eb7b518a56e)

*Si le bug ce reproduit, merci de rouvrir cette issue et de ne pas en créer une nouvelle.*
