### ISSUE TITLE
[Bug]: Slide vers la gauche ou droite dans l'EDT

### ISSUE THREAD

**Issue by lucas-luchack** [PapillonApp/papillon-v4#18]
### Description du bug

Lors de l'affichage de l'EDT il est possible de déplacer le centrage de l'écran de gauche à droite et inversement lors du swipe. (Ceci ne change donc pas la date)

### Etapes à reproduire

1. Aller sur l'EDT
2. Glisser de droite à gauche (au niveau du bouton ajout au calendrier c'est l'endroit où cela marche le mieux)

### Comportement attendu

Changer la date et ne pas permettre de décentrer les items

### Appareil

Xiaomi

### OS

Android 10

### Version

4.1b.2

### Environnement

PWA Stable (v3.pronote.plus)

**Comment by ecnivtwelve** [comment]
Ouais faudrait que je désactive le scroll horizontal sous Android, c'est fait pour utiliser l'effet bounce de Safari de base

**Comment by ecnivtwelve** [comment]
Fixé depuis quelques temps
