### ISSUE TITLE
[BUG] Connexion via géolocalisation non fonctionnelle

### ISSUE THREAD

**Issue by TheTiger72** [PapillonApp/papillon-v4#23]
### Description du bug

Cela affiche une erreur lors de la connexion

### Etapes à reproduire

1. Lancer l’app
2. Choisir une établissement
3. Se connecter

### Comportement attendu

Pouvoir se connecter sans erreur

### Appareil

iPhone 13

### OS

iOS 16.2 RC

### Version

Last

### Environnement

PWA Stable (v4.pronote.plus)

### Captures d'écran / vidéo

![66EF4723-A38D-41D5-A601-9FE1F389B4EA](https://user-images.githubusercontent.com/84013544/206449262-af5e2d29-0e14-49bc-9ba0-f53c1af8c32e.jpeg)

**Comment by ecnivtwelve** [comment]
Pouvons-nous avoir des infos sur ton académie et des détail sur ta procédure de connexion ?

**Comment by ecnivtwelve** [comment]
(fermé accidentellement)

**Comment by TheTiger72** [comment]
J'utilise la géo localisation pour trouver mon établissement, je le sélectionne, et je rentre mon id et mdp et j'ai l'erreur
Pour info mon académie est celle de nantes et j'ai réussi à me connecter quand même mais grâce à l'url pronote

**Comment by TheTiger72** [comment]
Ça fonctionne depuis les fix de @lucas-luchack 
Maintenant y'a juste un problème de CSS

**Comment by TheTiger72** [comment]
L'académie de Nantes a disparu dans la liste des ENT

**Comment by lucas-luchack** [comment]
Ceci est normal étant donné que l'académie de Nantes n'a pas d'ENT à proprement parler.
Les élèves doivent utiliser e-lyco pour ce connecter a l'ENT.

_Je tiens cependant à m'excuser, e-lyco n'était pas présent dans la liste, merci pour votre signalement_
