### ISSUE TITLE
[Bug]: "npm i" impossible d'installer vite

### ISSUE THREAD

**Issue by WiBlum** [PapillonApp/papillon-v4#24]
### Description du bug

Étant possesseur d'un Raspberry Pi 400 avec Ubuntu installé dessus, je me suis dis que installer Papillon dessus pourait être sympa pour y avoir accès pour tout mes appareil en local.
J'ai testé sur mon PC sous windows que je dois reset dans pas longtemps du à plusieurs bugs sur windows 11 :/ et tout parait normal et marche normalement, je n'ai pas testé si j'arrivais à me connecter à mon ent et si tout marchait mais le package vite de npm marchais correctement.

Sur mon Raspberry Pi, c'est un autre problème.
Voici les information de l'os installé dessus :
```
root@ubuntu:/home/Docker/Container/pronote# uname -a
Linux ubuntu 5.15.0-1021-raspi #23-Ubuntu SMP PREEMPT Fri Nov 25 15:27:43 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

Comme vous pouvez le voir j'ai aussi essayé de l'installer dans un container mais rien de change, toujours la meme erreur.

### Etapes à reproduire

1.  git clone [repo]
2.  npm i

### Comportement attendu

F:\Downloads\Papillon-main>npm i

up to date, audited 1380 packages in 5s

122 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

F:\Downloads\Papillon-main>

### Appareil

Raspberry Pi 400 (4Gb)

### OS

Ubuntu Desktop

### Version

5.15.0-1021-raspi

### Environnement

PWA Stable (v4.pronote.plus)

### Captures d'écran / vidéo

[2022-12-10T19_35_13_724Z-debug-0.log](https://github.com/PapillonApp/Papillon/files/10200983/2022-12-10T19_35_13_724Z-debug-0.log)

### Contexte supplémentaire

J'ai cherché quelques alternatives a ce problème mais je crois que ça ne change rien, les version aarch64 ne sont pas surportées par  npm vite :/
Je vais tout de meme tenter avec un serveur node.js dans un container ou apache2 mais je ne suis pas sûr :/

Merci de l'aide !

**Comment by sivelswhy** [comment]
C'est un peu direct et méchant mais ton support n'est pas vraiment relatif à Pronote+. En revanche il existe des discord avec des communautés énorme tel que [the programmer's hangout](https://discord.gg/programming)

**Comment by lucas-luchack** [comment]
*Ne concerne pas directement Papillon*

**Comment by vexcited** [comment]
J'aimerais ajouter que moi même j'utilise Vite sur mon Raspberry PI 4 (aarch64 aussi) et cela fonctionne très bien. Je suis sous Debian donc ça devrait pas être si différent que ça.

La seule différence c'est que j'utilise pas NPM mais pnpm, cependant je pense que ça devrait rien changer ~

**Comment by moeenio** [comment]
@williamhelle J'ai jeté un coup d'oeil à ton log et il semble que tu es sur une version de node trop ancienne :
```
warn EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' }
warn EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
```
Tu as du faire par réflexe `sudo apt install node`, ce qui a installé node depuis les dépôts de debian/ubuntu, or ces derniers ne fournissent node qu'en version 12 (jusqu'à ubuntu [22.04](https://packages.ubuntu.com/jammy/nodejs), ubuntu [22.10](https://packages.ubuntu.com/kinetic/nodejs) inclut désormais la version 18). Je te recommendrais de réessayer en installant node depuis le [site officiel](https://nodejs.org/).
