### ISSUE TITLE
[Bug]: ENT "L'Éduc de Normandie"

### ISSUE THREAD

**Issue by sivelswhy** [PapillonApp/papillon-v4#26]
### Description du bug

Mon établissement possède un Pronote qui n'a pas d'identifiants Pronote. Nous devons nous connecter **forcément** par le site de [connexion de l'educ de normandie](https://connexion.l-educdenormandie.fr/?callback=https%3A%2F%2Fent.l-educdenormandie.fr%2Fcas%2Flogin%3Fservice%3Dhttps%253A%252F%252F0141763R.index-education.net%252Fpronote%252F), aucun code Pronote nous est fourni par l'école.
Ce bug ne peut forcément pas venir de mes codes, car depuis le site de connexion de l'educ de normandie, aucun problème pour me connecter.
Également, lors de la phrase sur la page de connexion "nous avons trouvé votre établissement ! vous êtes au COLLEGE A. MAUROIS et vous utilisez l'ENT **undefined**"
Toutes ces choses mises à bout m'empêche de me connecter avec une notification "Une erreur est survenue. Veuillez réessayer."

### Etapes à reproduire

1. Aller sur la page d'accueil de P+
2. Cliquer sur **"Trouver mon établissement"**
3. Entrer le code postal **"14800"**
4. Sélectionner l'établissement **"COLLEGE A. MAUROIS"**
5. Rentrer des identifiants Educonnect
6. Impossibilité de se connecter

### Comportement attendu

Je devrais être censé pouvoir me connecter normalement et utiliser P+

### Appareil

iPhone 8

### OS

iOS 16

### Version

4.0.0

### Environnement

PWA Stable (v4.pronote.plus)

### Captures d'écran / vidéo

https://i.imgur.com/GfRMn57.mp4

### Contexte supplémentaire

Si vous avez la nécessité de quelconque information en plus, je suis ouvert !

**Comment by ecnivtwelve** [comment]
On va voir ça !

**Comment by ecnivtwelve** [comment]
fix possible -> https://github.com/PapillonApp/Papillon/commit/e70512b87af0e091e0c33b838bd532b12206c9c4

**Comment by sivelswhy** [comment]
> fix possible -> [e70512b](https://github.com/PapillonApp/Papillon/commit/e70512b87af0e091e0c33b838bd532b12206c9c4)

Malheureusement rien de tout ça ne règle mon problème et le toast `Une erreur est survenue. Veuillez réessayer.` survient toujours.

**Comment by lucas-luchack** [comment]
Le fix précédent ainsi que la PR #28 ne permette pas de fixer le problème.
La PR est inutile, car n'a aucun endpoint côté API, le fix e70512b87af0e091e0c33b838bd532b12206c9c4 n'a pas la bonne URL.

Je vais faire un fix dans la journée ou demain.
___
*Je réouvre cette issue le temps que le fix soit bien fonctionnel*

**Comment by lucas-luchack** [comment]
Tentative de fix déployé -> 117429134653d7cd78f62bdfda82f1581588a449

**Comment by lucas-luchack** [comment]
Essai de te connecter avec la connexion avancé pour voir si cela fonctionne, il est probable que la géoloc marche toujours pas, mais c'est un problème récurant qu'il faudra rework pour un fix plus complet.

ENT :  `ENT l'Éduc de Normandie via EduConnect`
URL Pronote : `https://0141763r.index-education.net/pronote/eleve.html`
Identifiants : `ÉduConnect`

**Comment by lucas-luchack** [comment]
Normalement la géoloc fonctionne de nouveau, cependant je ne garantis rien...

**Comment by sivelswhy** [comment]
Alors... J'arrive à me connecter, mais la page rafraichie constamment (voir vidéo). J'ai l'impression que c'est la même chose que l'issue #13 

https://user-images.githubusercontent.com/82051273/209336708-b235eeba-aaf1-455e-b2e3-b6e72a1386b5.mp4

**Comment by sivelswhy** [comment]
Je souhaite rajouter, pour fix cela, je vais dans le local storage et je supprime tout, mais en regardant les value de mon local storage après m'être login et arrivant sur le même problème que le message précédent, mon local storage a des values `null` ou tout simplement vide : 
![image](https://user-images.githubusercontent.com/82051273/209353786-f7ce8b02-1221-4bba-9bc7-d916e3a429d4.png)
![image](https://user-images.githubusercontent.com/82051273/209353818-4f8e7736-64f1-4845-b558-03fff594a8e5.png)

**Comment by lucas-luchack** [comment]
Effectivement il y a un soucis, je regarde ça et je vous tiens informé

**Comment by lucas-luchack** [comment]
De mon côté cela fonctionne, je trouve ça plutôt étonnant...

**Comment by sivelswhy** [comment]
Maintenant, c'est l'ent et CAS qui apparait mais pas le reste
![image](https://user-images.githubusercontent.com/82051273/209410896-6b44f24d-e229-475c-af11-9db0e22eca26.png)

**Comment by sivelswhy** [comment]
J'ai essayé en insérant moi-même les values dans `loginData`, une value `userData` se créer avec mes bonnes infos, mais rien ne s'affiche (la page ne se rafraîchit plus à l'infini)
(Toutes les informations masquées signifie que ce sont les bonnes values)
![image](https://user-images.githubusercontent.com/82051273/209411082-efa09579-d462-4212-8f47-eaaf0fc817ba.png)

**Comment by sivelswhy** [comment]
My Bad en suppriment le cache (avec Ctrl + F5), ça marche !

**Comment by lucas-luchack** [comment]
Parfait !

**Comment by sivelswhy** [comment]
(ouais ça fait beaucoup de comments en 10 minutes) Alors : En téléchargeant le fichiers `.ics` de mes cours, il est tout simplement vide
`BEGIN:VCALENDAR`
`VERSION:2.0`
`PRODID:-//sebbo.net//ical-generator//EN`
`NAME:Ma journée du Invalid Date sur Pronote+`
`X-WR-CALNAME:Ma journée du Invalid Date sur Pronote+`
`END:VCALENDAR`
Alors que j'ai bien des devoirs pour la journée que j'ai sélectionnée
![image](https://user-images.githubusercontent.com/82051273/209411377-bfa67a87-3949-4025-9c28-29782368ae6a.png)
* Secondement : Le bouton `ajouter au calendrier` sur une matière ne marche tout simplement pas et ne fais rien à part faire une animation lorsque je click
![image](https://user-images.githubusercontent.com/82051273/209411455-1dc64b54-4e32-46b8-9ff7-289b9f0030d8.png)
* Troisièmement, **Dans les `notes`, ce sont mes notes du 1er trimestre qui apparaissent et non celles du second, comme pour ma moyenne etc.., tout les values au final**
* Quatrièmement, allant dans les paramètres pour voir les logs, ils y a des box rouges vides, et dans mon local storage, dans `errors`, il y a des strings vides :
`["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]`
* Cinquièmement (je fais pas si c'est uniquement du local ou pronote le prend en charge également) : Mettant un devoir comme fait, cela ne se met pas à jour sur pronote normal)
* Sixièmement (je comprend que vous ayez un peu la flemme de lire jusqu'ici) : Le 3 Janvier P+ ne m'affiche aucun cours alors que j'en ai bel et bien, et la request à l'url `https://python.api.just-tryon.tech/timetable?dateString=2022-12-24&token=XXXXXXXXXXXX` retourne un array vide:
![image](https://user-images.githubusercontent.com/82051273/209412098-ea490d32-b47a-45be-8775-5d1b9c4aee22.png)
![image](https://user-images.githubusercontent.com/82051273/209412120-5a5040ce-f57e-4057-b85d-4d378d5c5db9.png)


Voilà un peu tout ce que j'ai pu trouver, avec des fois des devoirs qui apparaissent pour un jour, l'autre fois non...
En espérant que ça puisse vous aider !

**Comment by lucas-luchack** [comment]
Merci pour ces précision, nous regarderons tout ça dès que possible.
Bonne fête de fin d'année à vous.

**Comment by ecnivtwelve** [comment]
> (ouais ça fait beaucoup de comments en 10 minutes) Alors : En téléchargeant le fichiers `.ics` de mes cours, il est tout simplement vide `BEGIN:VCALENDAR` `VERSION:2.0` `PRODID:-//sebbo.net//ical-generator//EN` `NAME:Ma journée du Invalid Date sur Pronote+` `X-WR-CALNAME:Ma journée du Invalid Date sur Pronote+` `END:VCALENDAR` Alors que j'ai bien des devoirs pour la journée que j'ai sélectionnée

Alors concernant le calendrier iCal c'est un bug dont j'avais connaissance qui demande pas un grand fix, mais j'ai pas encore pris le temps de m'y attarder... je fixerai ça d'ici peu !
