### ISSUE TITLE
[Bug]: Connexion impossible

### ISSUE THREAD

**Issue by vexcited** [PapillonApp/papillon-v4#29]
### Description du bug

Réponse API de `POST https://python.api.just-tryon.tech/generatetoken`:

```json
{"token": false, "error": "module 'pronotepy.ent' has no attribute 'undefined'"}
```

Je vois que dans le payload de la requête, il y a `cas: "undefined"`

### Etapes à reproduire

1. Choisir son établissement
2. Arriver sur la page de connexion: `https://v4.pronote.plus/setup_3`
3. Rentrer ses identifiants et cliquer sur "Se connecter".

### Comportement attendu

Connexion réussie je suppose ?

### Appareil

Raspberry PI 4B

### OS

DietPi (Debian)

### Version

8.12.1

### Environnement

PWA Stable (v4.pronote.plus)

**Comment by ecnivtwelve** [comment]
Pourrait-on connaitre le nom de ton académie/ENT + l'URL de la page de login de celle ci si tu peux ?

**Comment by vexcited** [comment]
L'instance Pronote de mon lycée est assez simple, `https://0870056n.index-education.net/pronote/?login=true`. J'ai ajouté `?login=true` pour bypass l'ENT.

En ce qui concerne justement l'ENT, c'est celle du LycéeConnecté en NAQ donc `mon.lyceeconnecte.fr/auth/login` pour la page de connexion.

**Comment by vexcited** [comment]
J'ai utilisé la méthode avancé et ça fonctionne, cependant ça serait cool d'avoir la séléction auto qui fonctionne :p

**Comment by sivelswhy** [comment]
> L'instance Pronote de mon lycée est assez simple, `https://0870056n.index-education.net/pronote/?login=true`. J'ai ajouté `?login=true` pour bypass l'ENT.
> 
> En ce qui concerne justement l'ENT, c'est celle du LycéeConnecté en NAQ donc `mon.lyceeconnecte.fr/auth/login` pour la page de connexion.

À propos de ça, saurais-tu comment récupérer mes identifiants Pronote car j'ai uniquement des identifiants ENT qui ensuite nous login automatiquement à Pronote. Et en essayant de faire l'option `Récupérer son identifiant et son mot de passe` et ensuite mettre l'adresse mail rentré sur mon ENT, cela indique que ça ne marche pas. Donc si quelqu'un saurait, j'en serais bien reconnaissant.
Parce qu'auparavant je me login(ais) exclusivement via mon ENT et je ne savais pas l'existence du paramètre `?login=true` mais le problème, c'est que P+ ne marche pas avec mon ENT.

**Comment by vexcited** [comment]
>  uniquement des identifiants ENT qui ensuite nous login automatiquement à Pronote

Si ton établissement ne t'as pas donné d'identifiants Pronote, t'es obligé d'utiliser l'ENT malheureusement et tu peux rien y faire jusqu'à preuve du contraire.

**Comment by lucas-luchack** [comment]
Ce problème a déjà été signaler, je le subi moi-même.
Un fix a été déployé il y a une semaine si je ne me trompe pas.

Cependant, l'API n'a pas encore récupéré cette update ce qui fait que la connexion avec l'ENT **Lycée Connecté** n'est pas fonctionnelle pour le moment.

A noter que la connexion via cet ENT ce fait via ses identifiants *ÉduConnect* et non les identifiants locaux.
___
*Je ferme l'issue car il ne faut qu'attendre que le fix soit pris en compte par notre API, si après le fix le problème survient de nouveau, n'hésitez pas a rouvrir cette issue.*

**Comment by vexcited** [comment]
> A noter que la connexion via cet ENT ce fait via ses identifiants _ÉduConnect_ et non les identifiants locaux.

Bah ça tombe mal car mon établissement ne nous a jamais fourni d'identifiants EduConnect.

Cependant j'ai les identifiants locaux et les identifiants Pronote.

**Comment by lucas-luchack** [comment]
Malheureusement pour le moment il n'est pas prévu d'ajouter la connexion locale, cela pourrait tout de même arriver à un moment.

Pour contrer ce problème, utilisez les identifiants Pronote. Pour cela utiliser la connexion avancée (avec URL) et renseigner vous même les informations en ajouter `eleve.html?login=true` à la fin de l'url de votre établissement.
