### ISSUE TITLE
[Bug]: Notes du 1er trimestre

### ISSUE THREAD

**Issue by sivelswhy** [PapillonApp/papillon-v4#30]
### Description du bug

Dans l'onglet `Notes` de Pronote+, ce sont les notes du premier trimestre qui s'affichent et non celles du second

### Etapes à reproduire

1. Ouvrir Pronote+
2. Aller sur la page `Notes`
3. Observer

### Comportement attendu

Je devrais pouvoir voir mes notes (et ma moyenne) du second trimestre ou sinon pouvoir switch entre le premier et le second

### Appareil

Chrome Version 108.0.5359.125 (Build officiel) (64 bits)

### OS

Windows 11 22H2

### Version

4.0.0

### Environnement

PWA Stable (v4.pronote.plus)

**Comment by lucas-luchack** [comment]
Fixé dans l'API

**Comment by sivelswhy** [comment]
Je ne sais pas si c'est un bug qui vient de ma part mais le graph des notes est juste blanc.

![image](https://user-images.githubusercontent.com/82051273/210897285-c005bbf6-ed8b-4d2d-9f17-6e70ede94edf.png)

**Comment by Rexxt** [comment]
Quel graphe de notes ?
