### ISSUE TITLE
[Bug]: Affichage des notes

### ISSUE THREAD

**Issue by vexcited** [PapillonApp/papillon-v4#31]
### Description du bug

Quand on a deux matières qui ont exactement le même nom, seulement une des deux matières s'affiche, par exemple j'ai deux `ENSEIGNEMENT SCIENTIFIQUES` dans Pronote, un pour la Physique et l'autre pour la SVT.

Sauf que dans Pronote+, j'en ai qu'une des deux qui apparaît dans la liste.

### Etapes à reproduire

1. Se connecter
2. Aller dans la page des notes
3. Constater le problème

### Comportement attendu

Affichage des deux matières dans deux catégories séparés.

### Appareil

Raspberry Pi 4B

### OS

Arch-Linux

### Version

v4 - Stable

### Environnement

PWA Stable (v4.pronote.plus)

### Captures d'écran / vidéo

Réponse de l'API pour montrer que j'ai bien deux matières ES (ne faites pas attention à mes moyennes catastrophiques)

![Screenshot_20221224_161621](https://user-images.githubusercontent.com/59152884/209442094-009c1b01-2fcc-430b-9d7f-d541f2d6ea2a.jpg)

**Comment by BloomyInDev** [comment]
Perso les notes se mettent dans la même partie (les 2 enseignements scientifiques se melangent)

**Comment by lucas-luchack** [comment]
Effectivement, ce bug a été constater et nous travaillons pour le résoudre, merci pour votre signalement.

**Comment by lucas-luchack** [comment]
Fixé dans la nouvelle version
