### ISSUE TITLE
[Bug]: Changement de date

### ISSUE THREAD

**Issue by Skythrew** [PapillonApp/papillon-v4#37]
### Description du bug

Le changement de date dans le calendrier de la navbar rafraîchit le contenu d'autres onglets (cours <---> devoirs) sans rafraîchir le calendrier de ces onglets.

### Etapes à reproduire

1. Se connecter
2. Parcourir les onglets cours et devoirs au moins une fois (pour effectuer un mount des composants)
3. Changer la date sur un des deux onglets
4. Aller vérifier la date et le contenu de l'autre onglet 

### Comportement attendu

Le changement de date dans le calendrier de la navbar devrait rafraîchir le contenu d'autres onglets (cours <---> devoirs) tout en rafraîchissant le calendrier de ces onglets.

### Appareil

Minisforum B550

### OS

Linux

### Version

4.2.1

### Environnement

PWA Stable (v4.pronote.plus)

**Comment by lucas-luchack** [comment]
Déjà répondu sur Discord par @ecnivtwelve 
\+ bug non réalisable sur la nouvelle version
