### ISSUE TITLE
[Bug]: Impossible de se connecter

### ISSUE THREAD

**Issue by isteewx** [PapillonApp/papillon-v4#38]
### Description du bug

Quel que soit ma méthode de localisation de mon établissement, la connexion échoue.
Quels que soit les identifiants, aussi.

### Etapes à reproduire

1. Utiliser n'importe quelle methode pour ajouter un compte
2. Enter n'importe quels identifiants, meme faux
3. Observer pendant que rien ne se passe

### Comportement attendu

Une connexion réussie

### Appareil

Ordinateur

### OS

Windows

### Version

11 22H2

### Environnement

PWA Stable (v4.pronote.plus)

### Captures d'écran / vidéo

https://user-images.githubusercontent.com/37043298/211643023-40a25afa-b51c-4fcd-8987-e25e234fe6e9.mp4

**Comment by lucas-luchack** [comment]
**Il sera impossible pour vous d'utiliser Papillon.**

En effet, votre établissement à bloqué toute connexion via l'URL, ainsi, notre API ne peux ce connecter sur votre serveur Pronote.

La méthode avec QR Code ne permettra sûrement pas non plus de fixé ce problème.

> *Voir [le lien Pronote de l'établissement](https://0930830x.index-education.net/pronote/eleve.html) pour comprendre. La page est une page 403 : accès interdit. Notre API ne peux joindre le serveur.*

**Comment by isteewx** [comment]
C'est regrettable, quoiqu'il arrive, merci de la rapidité de votre réponse :)

**Comment by lucas-luchack** [comment]
Si vous avez des renseignement concernant la méthode que vous utilisez pour vous connecter afin de voir ce que nous pouvons faire nous en serons ravis.

Encore une fois, désolé pour ce problème...

**Comment by Rexxt** [comment]
> > _Voir [le lien Pronote de l'établissement](https://0930830x.index-education.net/pronote/eleve.html) pour comprendre. La page est une page 403 : accès interdit. Notre API ne peux joindre le serveur._

Il semble que le lien Pronote de l'établissement fonctionne à la datte d'aujourd'hui, le problème est donc à revoir/revérifier.

**Comment by isteewx** [comment]
Le probleme est toujours présent, malheureusement.

**Comment by lucas-luchack** [comment]
Effectivement, la page est toujours en 403 ce qui est donc normal comme j'ai déjà pu le dire précédemment.

Tant que la page Pronote ne sera pas accessible publiquement il sera impossible d'utiliser Papillon. (v4 ou v5)
