### ISSUE TITLE
[Bug]: Connexion via l'ent de l'académie de Clermont-Ferrand impossible depuis Papillon v4

### ISSUE THREAD

**Issue by moeenio** [PapillonApp/papillon-v4#39]
### Description du bug

Connexion impossible a un établissement via l'ent de l'académie de Clermont-Ferrand, que ce soit par géolocalisation ou par URL.

### Etapes à reproduire

Essayer de se connecter à un établissement de l'Académie de Clermont-Ferrand via le portail ent de l'Académie de Clermont-Ferrand, d'abord via la géolocalisation (par exemple code postal 63000) puis via URL (avec un établissement dispo dans la liste)

### Comportement attendu

Pouvoir se connecter

### Appareil

pas d'importance àma

### OS

Android 9

### Version

Inconnu

### Environnement

PWA Stable (v4.pronote.plus)

### Contexte supplémentaire

Merci pour tout votre travail!

Par contre ça ne fait pas de mal de répondre si l'on demande à transférer un ticket de papillon-python.

**Comment by lucas-luchack** [comment]
Je n'avais pas vu que vous aviez demandé de transférer l'issue.

Cependant concernant votre issue, la connexion avec l'ENT Ma Classe en Auvergne Rhône Alpes fonctionne parfaitement d'après les retours d'API, si la connexion ne fonctionne pas avec votre établissement pouvez-vous fournir les logs d'erreur de l'API, merci.

**Comment by moeenio** [comment]
Ho mais je viens de voir que ça marche très bien sur un ordinateur où je n'ai jamais utilisé l'appli! De plus je remarque que les textes sont différents. Je suppose donc que Firefox sur mon téléphone utilise une ancienne version gardée en cache...

Faudrait éventuellement réfléchir à contrer ça

**Comment by lucas-luchack** [comment]
Le problème est déjà réglé dans la prochaine version.
Merci pour votre issue 👋🏻
