### ISSUE TITLE
[Bug]: Impossible de télécharger le calendrier sur IOS 16.0.3

### ISSUE THREAD

**Issue by goldendu54** [PapillonApp/papillon-v4#41]
### Description du bug

Quand j'appuie sur Ajouter cette journée au calendrier j'ai l'erreur de Safari ne peut télécharger ce fichier.

### Etapes à reproduire

1. appuyer sur Ajouter cette journée au calendrier dans la catégorie Cours

### Comportement attendu

j'attend que cette journée soit mise sur mon calendrier sur mon téléphone 

### Appareil

iPhone 11

### OS

IOS 16.0.3

### Version

4.2.1

### Environnement

iOS Profil d'installation

### Contexte supplémentaire

je me suis connecter via educonnect

**Comment by TheTiger72** [comment]
J'ai le même problème avec un iPhone 13 sous iOS 16.3 beta 2

**Comment by Rexxt** [comment]
La dernière fois que j'avais regardé l'API Python, la fonctionnalité d'exportation vers le format iCal n'était pas opérationnelle. Sauf erreur de ma part, cela n'a pas été mis à jour. Je vais cependant m'intéresser à la source du problème (qui je crois émane du wrapper qu'on utilise). Nous vous tiendrons tous au courant.

**Comment by lucas-luchack** [comment]
Ce bug est normal, @ecnivtwelve en a la connaissance mais il ne sera pas fixé dans cette version
