### ISSUE TITLE
Moyenne générale perso et classe

### ISSUE THREAD

**Issue by BloomyInDev** [PapillonApp/papillon-v4#42]
### Description du bug

La moyenne de la classe et générale ne s'affiche pas sur mon compte

### Etapes à reproduire

1. Aller sur papillon
2. Se logger

### Comportement attendu

Voir les moyennes 😀

### Appareil

Samsung S10e

### OS

Android 12 / OneUI 4.1

### Version

?

### Environnement

PWA Stable (v4.pronote.plus)

### Contexte supplémentaire

Je suis sur educonnect si vous avez besoin de savoir

**Comment by BloomyInDev** [comment]
Version 4.2.1 j'avais oublié ce détail

**Comment by BloomyInDev** [comment]
Autres bugs trouvés:
- si on change la date sa plante l'affichage de l'emploi du temps
- les profs absents ne remontent pas dans l'emploi du temps

**Comment by Rexxt** [comment]
Ca semble être un problème venant de ta session ou de l'instance sur laquelle est ton compte.
Essaie de demander à qqn d'autre de ton établissement de se connecter à Papillon 4 et dis-nous si le problème s'applique à lui/elle.

**Comment by lucas-luchack** [comment]
Ne sera pas réglé dans cette version.
Cependant, concernant les profs absents si vous avez de quelconques informations supplémentaires faites en nous part pour que ce soucis ne se reproduise pas sur `Papillon v5`
