### ISSUE TITLE
[Bug]: Affichage de note négative

### ISSUE THREAD

**Issue by Gamers-geek** [PapillonApp/papillon-v4#43]
### Description du bug

Affichage d'une note négative lorsque la note est "Absent"

### Etapes à reproduire

**Prérequis :** avoir une note "Abs"
1. Se connecter
2. Aller dans l'onglet note
3. La note durant que vous avez eu en absent est affiché négativement.

### Comportement attendu

Afficher "Absent/20" au lieu de "-1,00/"20

### Appareil

HP Prodesk

### OS

Windows 10

### Version

Windows 1809 (Version de l'OS : 17763.1577)

### Environnement

PWA Stable (v4.pronote.plus)

### Captures d'écran / vidéo

Affichage Pronote : 
![image](https://user-images.githubusercontent.com/40898202/212924796-3cb3fe70-c8d1-40e7-878c-b4f4b0fd56d7.png)
Affichage Pronote+ : 
![image](https://user-images.githubusercontent.com/40898202/212925036-2c939d4b-38fb-4afe-b15f-8801fee51570.png)
(les notes moy, min et max ont volontairement été cachée)

**Comment by Rexxt** [comment]
Cela est probablement dû à la manière dont les notes sont stockées et sont rendues par Pronote.
On va tenter de régler ça au plus vite.

**Comment by lucas-luchack** [comment]
Ceci est tout à fait normal depuis la fait que la V4 est `DEPRECATED`.
Cela fait 1 mois que les notes apparaissent comme cela. **Nous n'avons pas prévu de le fixer au vu des modification à faire et de la gène que cela occasionne**, cela survient car l'API a subi des modification pour Papillon v5 ce qui la rends incompatible sur certains points avec la v4.
*Si j'ai vraiment le temps je changerais ça...*

P.S.:
> Cela est probablement dû à la manière dont les notes sont stockées et sont rendues par Pronote.
-> *Non, il s'agit d'un retour normal que j'ai choisi de manière arbitraire côté API*

**Comment by Rexxt** [comment]
> retour normal

😬😬
> que *j'*ai choisi

😬😬😬
> de manière arbitraire

😬😬😬😬

**Comment by Rexxt** [comment]
\+ le fait que l'API ait été changée pour la v5 et que ça se répercute sur la v4, je trouve que c'est un manque de professionnalisme : l'hébergeur ne sépare pas un serveur production d'un serveur beta test !! Je suis déçu que vous ayez négligé le versionnage de l'API, c'est pourquoi je propose une mise à jour de l'API, de la v4 et de la v5 pour séparer les deux.
