### ISSUE TITLE
[DEV] Problème avec les gesture

### ISSUE THREAD

**Issue by lucas-luchack** [PapillonApp/papillon-v4#7]
Le changement de jour dans l'EDT ne marche pas parfaitement avec les gesture.

La zone sensible au toucher est seulement celle où des cours apparaissent, ce qui n'est pas naturel lorsqu'il n'y aucun cours ou peu de cours où il faut alors chercher le doigt tout en haut de la page.

**Comment by ecnivtwelve** [comment]
fix ici https://github.com/PapillonApp/papillon-v4/commit/68ce173df98b91e991d73cbfa2b4fbe18e796c52
